window.PROSPECTS = [
  {
    "id": "daily-2026-09-01-l-uchronie-saint-sebastien-sur-loire",
    "code": "MENU01092601",
    "name": "L'uchronie",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 316,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-lezzet-food-kebab-saint-sebastien-sur-loire",
    "code": "MENU01092602",
    "name": "LEZZET FOOD KEBAB",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 265,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-o-burger-carquefou-carquefou",
    "code": "MENU01092603",
    "name": "Ô burger Carquefou",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 539,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-lideal-saint-sebastien-sur-loire",
    "code": "MENU01092604",
    "name": "L’idéal",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 576,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-gourmandise-saint-sebastien-sur-loire",
    "code": "MENU01092605",
    "name": "La Gourmandise",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 242,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-chez-lizette-carquefou",
    "code": "MENU01092606",
    "name": "Chez Lizette",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.5,
    "reviews": 377,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-krousty-factory-reze",
    "code": "MENU01092607",
    "name": "Krousty Factory",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 107,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-bistro-du-velo-reze",
    "code": "MENU01092608",
    "name": "Bistro du Vélo",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.4,
    "reviews": 405,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-evidence-restaurant-saint-sebastien-sur-loire",
    "code": "MENU01092609",
    "name": "Evidence Restaurant",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 71,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-fringale-carquefou-carquefou",
    "code": "MENU01092610",
    "name": "La Fringale CARQUEFOU",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 55,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-113-food-reze",
    "code": "MENU01092611",
    "name": "113 Food",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 45,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-savannah-pizzeria-reze",
    "code": "MENU01092612",
    "name": "Savannah pizzeria",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 45,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-brasserie-de-carquefou-carquefou",
    "code": "MENU01092613",
    "name": "LA BRASSERIE DE CARQUEFOU",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.5,
    "reviews": 68,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-maioann-carquefou",
    "code": "MENU01092614",
    "name": "Maioann",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 230,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-glouton-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "MENU01092615",
    "name": "Glouton Saint-Sébastien-sur-Loire",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 1887,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-meilleurtaux-saint-sebastien-sur-loire-courtier-en-credit-immobilier-saint-sebastien-sur-loire",
    "code": "STAGE01092616",
    "name": "Meilleurtaux Saint-Sébastien-sur-Loire courtier en crédit immobilier",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 625,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-l-art-de-loger-carquefou",
    "code": "STAGE01092617",
    "name": "L'Art de Loger",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 252,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-era-reze-immobilier-reze",
    "code": "STAGE01092618",
    "name": "AGENCE IMMOBILIERE ERA REZE IMMOBILIER",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 188,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-reze-bras-immobilier-reze-reze",
    "code": "STAGE01092619",
    "name": "Agence immobilière Rezé - BRAS Immobilier Rezé",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.7,
    "reviews": 183,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-iconfort-votre-agence-immobiliere-a-reze-reze",
    "code": "STAGE01092620",
    "name": "iconfort, votre agence immobilière à Rezé",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 143,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-maelenn-le-moelle-carquefou",
    "code": "STAGE01092621",
    "name": "Maelenn Le Moelle",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 113,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-l-adresse-carquefou-carquefou",
    "code": "STAGE01092622",
    "name": "Agence immobilière l'Adresse Carquefou",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.6,
    "reviews": 190,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-investir-l-avenir-immobilier-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "STAGE01092623",
    "name": "Investir l'avenir Immobilier Saint Sebastien sur Loire",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 108,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-l-etude-immobiliere-carquefou-carquefou",
    "code": "STAGE01092624",
    "name": "L'Etude Immobilière Carquefou",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 131,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-jeanne-le-gall-conseillere-en-immobilier-et-experte-dans-lemission-100-immo-reze-region-nantaise-reze",
    "code": "STAGE01092625",
    "name": "Jeanne LE GALL - Conseillère en immobilier et Experte dans l’émission 100% Immo - Rezé/Région nantaise",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 69,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-j-b-electricite-les-sorinieres",
    "code": "VIT01092626",
    "name": "J.B Electricité",
    "city": "Les Sorinières",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 71,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-abcp-antoine-begue-chauffage-plomberie-thouare-sur-loire",
    "code": "VIT01092627",
    "name": "ABCP Antoine Bégué Chauffage Plomberie",
    "city": "Thouaré-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 36,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-sabot-stephane-saint-sebastien-sur-loire",
    "code": "VIT01092628",
    "name": "SABOT Stéphane",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 47,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-ener-j-reze",
    "code": "VIT01092629",
    "name": "ENER'J",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 22,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-lion-electricite-reze",
    "code": "VIT01092630",
    "name": "Lion Electricité",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 9,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-elec-solution-reze",
    "code": "VIT01092631",
    "name": "ELEC-SOLUTION",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-sim-elec-reze",
    "code": "VIT01092632",
    "name": "Sim'elec",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 24,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-services-energies-sarl-saint-sebastien-sur-loire",
    "code": "VIT01092633",
    "name": "Services Energies SARL",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 1732,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-crearea-electricite-plomberie-salle-de-bain-cuisine-reze",
    "code": "VIT01092634",
    "name": "CREAREA ELECTRICITE / PLOMBERIE / SALLE DE BAIN & CUISINE",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 106,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-marion-energies-reze",
    "code": "VIT01092635",
    "name": "MARION ENERGIES",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 132,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-chauffage-and-co-nantes",
    "code": "VIT01092636",
    "name": "Chauffage And Co",
    "city": "Nantes",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 87,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-lagence-energie-carquefou",
    "code": "VIT01092637",
    "name": "Lagence Energie",
    "city": "Carquefou",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 54,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-codefel-recherche-de-fuite-d-eau-saint-sebastien-sur-loire",
    "code": "VIT01092638",
    "name": "Codefel - Recherche de fuite d'eau",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 25,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-artisan-pereira-depannage-carquefou",
    "code": "VIT01092639",
    "name": "Artisan Pereira DEPANNAGE",
    "city": "Carquefou",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-h2e-electricite-reze",
    "code": "VIT01092640",
    "name": "H2E Electricite",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-iron-bodyfit-carquefou-carquefou",
    "code": "REACT01092641",
    "name": "Iron Bodyfit Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 186,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-eudaimonia-social-sport-club-carquefou",
    "code": "REACT01092642",
    "name": "EUDAIMONIA Social Sport Club",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 607,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-kutzbarber44-saint-sebastien-sur-loire",
    "code": "REACT01092643",
    "name": "KutzBarber44",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 337,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-la-douce-heure-institut-de-beaute-nantes-saint-sebastien-sur-loire",
    "code": "REACT01092644",
    "name": "La Douce Heure - Institut de beauté Nantes",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 228,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-l-orange-bleue-mon-coach-fitness-carquefou-carquefou",
    "code": "REACT01092645",
    "name": "L'Orange bleue Mon Coach Fitness - Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 151,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-birdal-barber-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "REACT01092646",
    "name": "Birdal Barber - SAINT SEBASTIEN SUR LOIRE",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 149,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-csl-automobiles-reze",
    "code": "REACT01092647",
    "name": "Csl Automobiles",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 306,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-carglass-pare-brise-reze-reze",
    "code": "REACT01092648",
    "name": "CARGLASS Pare-Brise Reze",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 1162,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-elancia-carquefou-carquefou",
    "code": "REACT01092649",
    "name": "Elancia Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.6,
    "reviews": 280,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-bpm-cars-fiat-reze-reze",
    "code": "REACT01092650",
    "name": "BPM Cars - Fiat Rezé",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.6,
    "reviews": 359,
    "sample": "reactivation/"
  }
];
