window.PROSPECTS = [
  {
    "id": "daily-2026-09-01-l-uchronie-saint-sebastien-sur-loire",
    "code": "MENU01092601",
    "name": "L'uchronie",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 316,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-lezzet-food-kebab-saint-sebastien-sur-loire",
    "code": "MENU01092602",
    "name": "LEZZET FOOD KEBAB",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 265,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-o-burger-carquefou-carquefou",
    "code": "MENU01092603",
    "name": "Ô burger Carquefou",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 539,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-lideal-saint-sebastien-sur-loire",
    "code": "MENU01092604",
    "name": "L’idéal",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 576,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-gourmandise-saint-sebastien-sur-loire",
    "code": "MENU01092605",
    "name": "La Gourmandise",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 242,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-chez-lizette-carquefou",
    "code": "MENU01092606",
    "name": "Chez Lizette",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.5,
    "reviews": 377,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-krousty-factory-reze",
    "code": "MENU01092607",
    "name": "Krousty Factory",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 107,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-bistro-du-velo-reze",
    "code": "MENU01092608",
    "name": "Bistro du Vélo",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.4,
    "reviews": 405,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-evidence-restaurant-saint-sebastien-sur-loire",
    "code": "MENU01092609",
    "name": "Evidence Restaurant",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 71,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-fringale-carquefou-carquefou",
    "code": "MENU01092610",
    "name": "La Fringale CARQUEFOU",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 55,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-113-food-reze",
    "code": "MENU01092611",
    "name": "113 Food",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 45,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-savannah-pizzeria-reze",
    "code": "MENU01092612",
    "name": "Savannah pizzeria",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 45,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-la-brasserie-de-carquefou-carquefou",
    "code": "MENU01092613",
    "name": "LA BRASSERIE DE CARQUEFOU",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.5,
    "reviews": 68,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-maioann-carquefou",
    "code": "MENU01092614",
    "name": "Maioann",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 230,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-glouton-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "MENU01092615",
    "name": "Glouton Saint-Sébastien-sur-Loire",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 1887,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-01-meilleurtaux-saint-sebastien-sur-loire-courtier-en-credit-immobilier-saint-sebastien-sur-loire",
    "code": "STAGE01092616",
    "name": "Meilleurtaux Saint-Sébastien-sur-Loire courtier en crédit immobilier",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 625,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-l-art-de-loger-carquefou",
    "code": "STAGE01092617",
    "name": "L'Art de Loger",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 252,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-era-reze-immobilier-reze",
    "code": "STAGE01092618",
    "name": "AGENCE IMMOBILIERE ERA REZE IMMOBILIER",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 188,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-reze-bras-immobilier-reze-reze",
    "code": "STAGE01092619",
    "name": "Agence immobilière Rezé - BRAS Immobilier Rezé",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.7,
    "reviews": 183,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-iconfort-votre-agence-immobiliere-a-reze-reze",
    "code": "STAGE01092620",
    "name": "iconfort, votre agence immobilière à Rezé",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 143,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-maelenn-le-moelle-carquefou",
    "code": "STAGE01092621",
    "name": "Maelenn Le Moelle",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 113,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-agence-immobiliere-l-adresse-carquefou-carquefou",
    "code": "STAGE01092622",
    "name": "Agence immobilière l'Adresse Carquefou",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.6,
    "reviews": 190,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-investir-l-avenir-immobilier-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "STAGE01092623",
    "name": "Investir l'avenir Immobilier Saint Sebastien sur Loire",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 108,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-l-etude-immobiliere-carquefou-carquefou",
    "code": "STAGE01092624",
    "name": "L'Etude Immobilière Carquefou",
    "city": "Carquefou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 131,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-jeanne-le-gall-conseillere-en-immobilier-et-experte-dans-lemission-100-immo-reze-region-nantaise-reze",
    "code": "STAGE01092625",
    "name": "Jeanne LE GALL - Conseillère en immobilier et Experte dans l’émission 100% Immo - Rezé/Région nantaise",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 69,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-01-j-b-electricite-les-sorinieres",
    "code": "VIT01092626",
    "name": "J.B Electricité",
    "city": "Les Sorinières",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 71,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-abcp-antoine-begue-chauffage-plomberie-thouare-sur-loire",
    "code": "VIT01092627",
    "name": "ABCP Antoine Bégué Chauffage Plomberie",
    "city": "Thouaré-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 36,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-sabot-stephane-saint-sebastien-sur-loire",
    "code": "VIT01092628",
    "name": "SABOT Stéphane",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 47,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-ener-j-reze",
    "code": "VIT01092629",
    "name": "ENER'J",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 22,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-lion-electricite-reze",
    "code": "VIT01092630",
    "name": "Lion Electricité",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 9,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-elec-solution-reze",
    "code": "VIT01092631",
    "name": "ELEC-SOLUTION",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-sim-elec-reze",
    "code": "VIT01092632",
    "name": "Sim'elec",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 24,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-services-energies-sarl-saint-sebastien-sur-loire",
    "code": "VIT01092633",
    "name": "Services Energies SARL",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 1732,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-crearea-electricite-plomberie-salle-de-bain-cuisine-reze",
    "code": "VIT01092634",
    "name": "CREAREA ELECTRICITE / PLOMBERIE / SALLE DE BAIN & CUISINE",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 106,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-marion-energies-reze",
    "code": "VIT01092635",
    "name": "MARION ENERGIES",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 132,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-chauffage-and-co-nantes",
    "code": "VIT01092636",
    "name": "Chauffage And Co",
    "city": "Nantes",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 87,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-lagence-energie-carquefou",
    "code": "VIT01092637",
    "name": "Lagence Energie",
    "city": "Carquefou",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 54,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-codefel-recherche-de-fuite-d-eau-saint-sebastien-sur-loire",
    "code": "VIT01092638",
    "name": "Codefel - Recherche de fuite d'eau",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 25,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-artisan-pereira-depannage-carquefou",
    "code": "VIT01092639",
    "name": "Artisan Pereira DEPANNAGE",
    "city": "Carquefou",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-h2e-electricite-reze",
    "code": "VIT01092640",
    "name": "H2E Electricite",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-01-iron-bodyfit-carquefou-carquefou",
    "code": "REACT01092641",
    "name": "Iron Bodyfit Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 186,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-eudaimonia-social-sport-club-carquefou",
    "code": "REACT01092642",
    "name": "EUDAIMONIA Social Sport Club",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 607,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-kutzbarber44-saint-sebastien-sur-loire",
    "code": "REACT01092643",
    "name": "KutzBarber44",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 337,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-la-douce-heure-institut-de-beaute-nantes-saint-sebastien-sur-loire",
    "code": "REACT01092644",
    "name": "La Douce Heure - Institut de beauté Nantes",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 228,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-l-orange-bleue-mon-coach-fitness-carquefou-carquefou",
    "code": "REACT01092645",
    "name": "L'Orange bleue Mon Coach Fitness - Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 151,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-birdal-barber-saint-sebastien-sur-loire-saint-sebastien-sur-loire",
    "code": "REACT01092646",
    "name": "Birdal Barber - SAINT SEBASTIEN SUR LOIRE",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 149,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-csl-automobiles-reze",
    "code": "REACT01092647",
    "name": "Csl Automobiles",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 306,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-carglass-pare-brise-reze-reze",
    "code": "REACT01092648",
    "name": "CARGLASS Pare-Brise Reze",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 1162,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-elancia-carquefou-carquefou",
    "code": "REACT01092649",
    "name": "Elancia Carquefou",
    "city": "Carquefou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.6,
    "reviews": 280,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-01-bpm-cars-fiat-reze-reze",
    "code": "REACT01092650",
    "name": "BPM Cars - Fiat Rezé",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.6,
    "reviews": 359,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-le-lion-et-l-agneau-nantes",
    "code": "MENU02092601",
    "name": "Le Lion et L'agneau",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 902,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-restaurant-art-n-blum-restaurant-nantes-nantes",
    "code": "MENU02092602",
    "name": "Restaurant Art'N Blum - Restaurant Nantes",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 748,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-pickles-nantes",
    "code": "MENU02092603",
    "name": "Pickles",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 1003,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-freia-nantes",
    "code": "MENU02092604",
    "name": "Freia",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 1525,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-gwaien-restaurant-nantes-nantes",
    "code": "MENU02092605",
    "name": "Gwaien Restaurant Nantes",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 731,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-la-mandale-restaurant-nantes",
    "code": "MENU02092606",
    "name": "La Mandale Restaurant",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 567,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-l-agave-nantes",
    "code": "MENU02092607",
    "name": "L'Agave",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 509,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-le-bistrot-basque-de-nantes-nantes",
    "code": "MENU02092608",
    "name": "Le Bistrot Basque de Nantes",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 1476,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-republique-restaurant-nantes-nantes",
    "code": "MENU02092609",
    "name": "République - Restaurant Nantes",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 740,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-le-petit-boucot-nantes",
    "code": "MENU02092610",
    "name": "Le Petit Boucot",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 422,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-le-bistro-des-enfants-nantais-nantes",
    "code": "MENU02092611",
    "name": "Le Bistro des Enfants Nantais",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 669,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-reginella-saint-sebastien-sur-loire",
    "code": "MENU02092612",
    "name": "Reginella",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 575,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-bunch-saint-sebastien-sur-loire",
    "code": "MENU02092613",
    "name": "Bunch",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 2460,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-palma-restaurant-saint-sebastien-sur-loire",
    "code": "MENU02092614",
    "name": "Palma - Restaurant",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 363,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-cara-saint-sebastien-sur-loire",
    "code": "MENU02092615",
    "name": "Cara",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 359,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-ferveur-saint-sebastien-sur-loire",
    "code": "MENU02092616",
    "name": "Ferveur",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 100,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-topette-esprit-bistrot-thouare-sur-loire",
    "code": "MENU02092617",
    "name": "Tôpette, Esprit Bistrot",
    "city": "Thouaré-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 104,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-les-tontons-cuisinent-saint-sebastien-sur-loire",
    "code": "MENU02092618",
    "name": "Les Tontons Cuisinent",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.3,
    "reviews": 1238,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-dhandi-snacking-thouare-thouare-sur-loire",
    "code": "MENU02092619",
    "name": "Dhandi Snacking Thouaré",
    "city": "Thouaré-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 54,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-pascal-blon-immobilier-sainte-luce-sur-loire-sainte-luce-sur-loire",
    "code": "STAGE02092620",
    "name": "Pascal BLON - Immobilier - Sainte Luce sur Loire",
    "city": "Sainte-Luce-sur-Loire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 22,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-caroline-sacrez-immobilier-martinique-sainte-luce",
    "code": "STAGE02092621",
    "name": "Caroline SACREZ IMMOBILIER MARTINIQUE",
    "city": "Sainte-Luce",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 26,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-le-secret-des-filles-espace-beaute-bien-etre-thouare-sur-loire",
    "code": "REACT02092622",
    "name": "Le Secret des Filles - Espace Beauté & Bien-être",
    "city": "Thouaré-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 183,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-institut-bel-et-zen-saint-herblain",
    "code": "REACT02092623",
    "name": "Institut Bel et Zen",
    "city": "Saint-Herblain",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 192,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-monauto-sud-loire-motrio-vertou",
    "code": "REACT02092624",
    "name": "Monauto Sud Loire - Motrio",
    "city": "Vertou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 172,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-squat-salle-de-sport-fort-de-france",
    "code": "REACT02092625",
    "name": "Squat, Salle de sport.",
    "city": "Fort-de-France",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 127,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-institut-terre-de-beaute-st-herblain-saint-herblain",
    "code": "REACT02092626",
    "name": "Institut Terre de Beauté - St Herblain",
    "city": "Saint-Herblain",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 102,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-renault-mecanauto-vertou",
    "code": "REACT02092627",
    "name": "Renault Mecan’Auto",
    "city": "Vertou",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.3,
    "reviews": 210,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-almafit-treillieres",
    "code": "REACT02092628",
    "name": "ALMAFIT",
    "city": "Treillières",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 63,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-institut-de-beaute-orphee-thouare-sur-loire",
    "code": "REACT02092629",
    "name": "Institut De Beauté Orphée",
    "city": "Thouaré-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 60,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-renault-dacia-atlantic-garage-agent-bouguenais",
    "code": "REACT02092630",
    "name": "Renault Dacia Atlantic Garage Agent",
    "city": "Bouguenais",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.6,
    "reviews": 86,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-kevin-coique-fitness-center-sainte-luce",
    "code": "REACT02092631",
    "name": "KEVIN COIQUE FITNESS CENTER",
    "city": "Sainte-Luce",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.8,
    "reviews": 34,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-eurorepar-garage-j-navinel-reze",
    "code": "REACT02092632",
    "name": "Eurorepar Garage J. Navinel",
    "city": "Rezé",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.5,
    "reviews": 83,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-aeroport-auto-service-bouguenais",
    "code": "REACT02092633",
    "name": "Aéroport Auto Service",
    "city": "Bouguenais",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.2,
    "reviews": 35,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-human-project-360-sainte-luce-sur-loire",
    "code": "REACT02092634",
    "name": "Human Project 360",
    "city": "Sainte-Luce-sur-Loire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 144,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-bar-restaurant-le-petit-jardin-saint-sebastien-sur-loire",
    "code": "MENU02092635",
    "name": "Bar Restaurant Le Petit Jardin",
    "city": "Saint-Sébastien-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 240,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-pub-viet-restaurant-bar-sainte-luce-sur-loire",
    "code": "MENU02092636",
    "name": "Pub Viet Restaurant & Bar",
    "city": "Sainte-Luce-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 5,
    "reviews": 195,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-restaurant-les-bons-vivants-vertou",
    "code": "MENU02092637",
    "name": "Restaurant Les Bons Vivants",
    "city": "Vertou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.9,
    "reviews": 210,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-glouton-vertou-vertou",
    "code": "MENU02092638",
    "name": "Glouton Vertou",
    "city": "Vertou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 1295,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-table-23-l-restaurant-grillades-au-feu-de-bois-l-carquefou-carquefou",
    "code": "MENU02092639",
    "name": "Table 23 l Restaurant grillades au feu de bois l Carquefou",
    "city": "Carquefou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.8,
    "reviews": 362,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-pilgrim-restaurant-nantes-nantes",
    "code": "MENU02092640",
    "name": "Pilgrim Restaurant Nantes",
    "city": "Nantes",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 763,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-tel-pere-tel-fils-vertou-vertou",
    "code": "MENU02092641",
    "name": "Tel Père Tel Fils Vertou",
    "city": "Vertou",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 427,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-les-maraichers-sainte-luce-sur-loire",
    "code": "MENU02092642",
    "name": "Les Maraichers",
    "city": "Sainte-Luce-sur-Loire",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 322,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-restaurant-du-pont-basse-goulaine",
    "code": "MENU02092643",
    "name": "Restaurant du Pont",
    "city": "Basse-Goulaine",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.7,
    "reviews": 775,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-valentina-reze",
    "code": "MENU02092644",
    "name": "Valentina",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 681,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-bcb-le-bistrot-reze",
    "code": "MENU02092645",
    "name": "BCB, Le Bistrot",
    "city": "Rezé",
    "category": "Restaurant",
    "offer": "Menu digital",
    "rating": 4.6,
    "reviews": 354,
    "sample": "menus/le-chantilly/"
  },
  {
    "id": "daily-2026-09-02-poinsot-immobilier-agence-immobiliere-ancenis-ancenis-saint-gereon",
    "code": "STAGE02092646",
    "name": "Poinsot Immobilier - Agence Immobilière Ancenis",
    "city": "Ancenis-Saint-Géréon",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 207,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-cabinet-blouin-immobilier-nort-sur-erdre",
    "code": "STAGE02092647",
    "name": "Cabinet Blouin Immobilier",
    "city": "Nort-sur-Erdre",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.7,
    "reviews": 217,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-immobiliere-era-vertou-vertou",
    "code": "STAGE02092648",
    "name": "Agence Immobilière ERA - Vertou",
    "city": "Vertou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 136,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-immobiliere-d-pro-immo-vertou-vertou",
    "code": "STAGE02092649",
    "name": "Agence immobilière D PRO Immo Vertou",
    "city": "Vertou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.7,
    "reviews": 142,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-caroline-roy-clisson",
    "code": "STAGE02092650",
    "name": "Caroline ROY",
    "city": "Clisson",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 75,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-mon-reve-immobilier-vertou",
    "code": "STAGE02092651",
    "name": "MON RÊVE IMMOBILIER",
    "city": "Vertou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 68,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-distinction-immobilier-agence-immobiliere-pornic",
    "code": "STAGE02092652",
    "name": "Distinction Immobilier - Agence Immobilière",
    "city": "Pornic",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 5,
    "reviews": 60,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-brochard-immobilier-clisson",
    "code": "STAGE02092653",
    "name": "Brochard Immobilier",
    "city": "Clisson",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.9,
    "reviews": 75,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-l-agence-locale-vertou",
    "code": "STAGE02092654",
    "name": "L'Agence Locale",
    "city": "Vertou",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 93,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-vivre-ici-saint-nazaire-presqu-ile-44-immobilier-saint-nazaire",
    "code": "STAGE02092655",
    "name": "VIVRE ICI SAINT NAZAIRE - Presqu'île 44 Immobilier",
    "city": "Saint-Nazaire",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.6,
    "reviews": 127,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-immobiliere-a-reze-nantes-sud-immobilier-reze",
    "code": "STAGE02092656",
    "name": "Agence immobilière à Rezé, Nantes Sud Immobilier",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 74,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-sainte-marie-pornic",
    "code": "STAGE02092657",
    "name": "Agence Sainte-Marie",
    "city": "Pornic",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.6,
    "reviews": 90,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-atout-sud-immobilier-reze-reze",
    "code": "STAGE02092658",
    "name": "Atout Sud Immobilier - Rezé",
    "city": "Rezé",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.7,
    "reviews": 59,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-du-vieux-port-pornic",
    "code": "STAGE02092659",
    "name": "Agence du Vieux Port",
    "city": "Pornic",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.5,
    "reviews": 96,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-acp-immobilier-machecoul-saint-meme",
    "code": "STAGE02092660",
    "name": "ACP Immobilier",
    "city": "Machecoul-Saint-Même",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.8,
    "reviews": 33,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-ferchau-immobilier-nort-sur-erdre",
    "code": "STAGE02092661",
    "name": "FERCHAU IMMOBILIER",
    "city": "Nort-sur-Erdre",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.5,
    "reviews": 39,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-agence-de-la-ria-agence-immobiliere-a-pornic-pornic",
    "code": "STAGE02092662",
    "name": "Agence de la Ria : Agence immobilière à Pornic",
    "city": "Pornic",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.4,
    "reviews": 41,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-filumena-office-immobilier-ancenis-saint-gereon",
    "code": "STAGE02092663",
    "name": "FILUMENA Office Immobilier",
    "city": "Ancenis-Saint-Géréon",
    "category": "Agence immobilière",
    "offer": "Home staging virtuel",
    "rating": 4.2,
    "reviews": 80,
    "sample": "home-staging/"
  },
  {
    "id": "daily-2026-09-02-ze-plombier-nantes-nantes",
    "code": "VIT02092664",
    "name": "Ze Plombier - Nantes",
    "city": "Nantes",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 362,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-toiture-expert-couvreurs-a-montreal-montreal-nord",
    "code": "VIT02092665",
    "name": "Toiture Expert - Couvreurs à Montréal",
    "city": "Montréal-Nord",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 220,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-novoclim-vigneux-de-bretagne",
    "code": "VIT02092666",
    "name": "Novoclim",
    "city": "Vigneux-de-Bretagne",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 370,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-expert-toiture-couvreur-coueron",
    "code": "VIT02092667",
    "name": "Expert Toiture Couvreur",
    "city": "Couëron",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 132,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-lb-couverture-toiture-zinguerie-peinture-44-coueron",
    "code": "VIT02092668",
    "name": "LB couverture, Toiture - Zinguerie - Peinture 44",
    "city": "Couëron",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 94,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-redois-couleurs-concepts-clisson",
    "code": "VIT02092669",
    "name": "Redois couleurs concepts",
    "city": "Clisson",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 61,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-cade-carquefou",
    "code": "VIT02092670",
    "name": "CADE",
    "city": "Carquefou",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 44,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-keeler-electric-inc-bernville",
    "code": "VIT02092671",
    "name": "Keeler Electric, Inc",
    "city": "Bernville",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 80,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-fl-eau-renov-bouguenais",
    "code": "VIT02092672",
    "name": "Fl'eau Rénov",
    "city": "Bouguenais",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 40,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-bm-energy-thouare-sur-loire",
    "code": "VIT02092673",
    "name": "BM Energy",
    "city": "Thouaré-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 37,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-sarl-le-mentec-electricite-plomberie-bouguenais",
    "code": "VIT02092674",
    "name": "SARL LE MENTEC : Électricité & Plomberie",
    "city": "Bouguenais",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 37,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-plombier-nantes-mattos-vincent-nantes",
    "code": "VIT02092675",
    "name": "Plombier Nantes MATTOS VINCENT",
    "city": "Nantes",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.5,
    "reviews": 133,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-dueau-plomberie-chauffage-plombier-nantes-nantes",
    "code": "VIT02092676",
    "name": "DU’EAU PLOMBERIE CHAUFFAGE - plombier Nantes",
    "city": "Nantes",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 26,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-apcs-derrien-saint-nazaire",
    "code": "VIT02092677",
    "name": "APCS Derrien",
    "city": "Saint-Nazaire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 64,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-pcbg-expert-qualipac-rge-et-chaudieres-basse-goulaine",
    "code": "VIT02092678",
    "name": "PCBG, expert QualiPAC, RGE et chaudières",
    "city": "Basse-Goulaine",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 20,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-e-solus-sainte-luce-sur-loire",
    "code": "VIT02092679",
    "name": "E-Solus",
    "city": "Sainte-Luce-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 60,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-couvreur-reze-ets-cazeneuve-expert-toiture-reze",
    "code": "VIT02092680",
    "name": "Couvreur Rezé - ETS Cazeneuve Expert Toiture",
    "city": "Rezé",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 20,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-dubois-plomberie-chauffage-heric",
    "code": "VIT02092681",
    "name": "Dubois Plomberie Chauffage",
    "city": "Héric",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 57,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-marionneau-guillaume-vallet",
    "code": "VIT02092682",
    "name": "Marionneau Guillaume",
    "city": "Vallet",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 36,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-couvreur-ancenis-artitoiture-vallons-de-l-erdre",
    "code": "VIT02092683",
    "name": "Couvreur ancenis Artitoiture",
    "city": "Vallons-de-l'Erdre",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 15,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-flm-elec-thouare-sur-loire",
    "code": "VIT02092684",
    "name": "FLM Elec",
    "city": "Thouaré-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 54,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-soluto-work-electricite-thouare-sur-loire",
    "code": "VIT02092685",
    "name": "SoluTo Work - Electricite",
    "city": "Thouaré-sur-Loire",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 14,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-magali-garrigou-composition-picturale-clisson",
    "code": "VIT02092686",
    "name": "Magali Garrigou - Composition Picturale",
    "city": "Clisson",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 7,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-ad-menuiserie-vallet",
    "code": "VIT02092687",
    "name": "Ad Menuiserie",
    "city": "Vallet",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 5,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-pro-tech-couverture-ancenis-saint-gereon",
    "code": "VIT02092688",
    "name": "Pro Tech Couverture",
    "city": "Ancenis-Saint-Géréon",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 5,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-couvreur-treillieres-j-atelier-couverture-demoussage-toiture-reparation-fuites-depannage-toit-etancheite-facadier-treillieres",
    "code": "VIT02092689",
    "name": "Couvreur Treillières J.Atelier Couverture, Demoussage Toiture, Réparation Fuites, Dépannage Toit, Étanchéité, Façadier",
    "city": "Treillières",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 5,
    "reviews": 5,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-leman-peinture-gorges",
    "code": "VIT02092690",
    "name": "Leman Peinture",
    "city": "Gorges",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 39,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-aymeric-diane-revelateurs-d-interieurs-decorateurs-artisans-peintres-et-tapissiers-a-clisson-clisson",
    "code": "VIT02092691",
    "name": "Aymeric & Diane - Révélateurs d'intérieurs - Décorateurs - Artisans peintres et tapissiers à Clisson",
    "city": "Clisson",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 16,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-landais-couverture-sarl-coueron",
    "code": "VIT02092692",
    "name": "Landais Couverture SARL",
    "city": "Couëron",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.8,
    "reviews": 33,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-antoine-peinture-guerande",
    "code": "VIT02092693",
    "name": "ANTOINE Peinture",
    "city": "Guérande",
    "category": "Artisan",
    "offer": "Vitrine artisan",
    "rating": 4.9,
    "reviews": 8,
    "sample": "artisans/k-thermique/"
  },
  {
    "id": "daily-2026-09-02-heric-depann-auto-depannage-remorquage-24h-24-7j-7-heric",
    "code": "REACT02092694",
    "name": "HERIC DEPANN'AUTO - Dépannage, remorquage 24h/24 - 7j/7",
    "city": "Héric",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 261,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-renault-guerande-groupe-idylauto-guerande",
    "code": "REACT02092695",
    "name": "Renault Guérande - Groupe Idylauto",
    "city": "Guérande",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.7,
    "reviews": 1110,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-accroche-coeur-saint-nazaire",
    "code": "REACT02092696",
    "name": "Accroche-Coeur",
    "city": "Saint-Nazaire",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.5,
    "reviews": 321,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-ad-expert-ng-auto-orvault",
    "code": "REACT02092697",
    "name": "AD EXPERT NG AUTO",
    "city": "Orvault",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.5,
    "reviews": 291,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-institut-guinot-pornic",
    "code": "REACT02092698",
    "name": "Institut Guinot",
    "city": "Pornic",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 76,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-yup-fitness-treillieres",
    "code": "REACT02092699",
    "name": "Yup Fitness",
    "city": "Treillières",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 5,
    "reviews": 72,
    "sample": "reactivation/"
  },
  {
    "id": "daily-2026-09-02-meca-dim-ancenis-saint-gereon",
    "code": "REACT020926100",
    "name": "Méca Dim",
    "city": "Ancenis-Saint-Géréon",
    "category": "Réactivation",
    "offer": "Réactivation clients",
    "rating": 4.9,
    "reviews": 91,
    "sample": "reactivation/"
  }
];
